name: Flutter Web Build & Deploy

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Set base href for GitHub Pages
        run: |
          # Replace <repo-name> with your repo name
          REPO_NAME="portifolio"
          # Replace placeholder in index.html
          sed -i "s|\$FLUTTER_BASE_HREF|/$REPO_NAME/|g" web/index.html

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Copy index.html to 404.html
        run: cp build/web/index.html build/web/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
